### PR TITLE
Override user.paste

### PR DESCRIPTION
**Pull request by knausj85**
Since a few commands use this, and it doesn't work currently, just use insert for now.

### CODE REVIEW

**Comment by knausj85** [comment]
Sorry, just noticed black reformatted things again. If you prefer otherwise, just let me know. It's what we use for the community repo.

**Comment by splondike** [comment]
Huh, I may have gotten confused by [your comment in the textarea todo issue](https://github.com/talonvoice/talon/issues/254#issuecomment-789355238). The issue (that you're fixing here) is pasting into the text area. Using paste to get text out of the textarea into other applications works fine? In my refactorings yesterday I swapped the 'draft submit' command to use insert() rather than user.paste(). Sounds like I should swap that back.

Happy to swap to the community repo code style.

**Comment by knausj85** [comment]
From my testing, any command that uses the default user.paste will fail in the draft window on both Mac OS X and Windows.
eg: https://github.com/knausj85/knausj_talon/blob/84e9a94d89a15d1318fb2c915cdcfb015d7aaae2/text/symbols.talon#L48

 since the default implementation is global,  this is a hack so at least the commands will work  in the draft window.  I figure this is better than silently failing.  does the default implementation work on linux?
 
 as far as I'm aware, user.paste will work for draft submit on only Mac OS X and Windows,  so using insert makes sense for that.  we could consider making  the logic operating system specific in the interim.

**Comment by splondike** [comment]
Pasting into the textarea works fine on Linux (Fedora 32) using 'paste that' or Ctrl+v, and using user.paste() for draft submit also works fine (at least with Gedit or Firefox).

Since luxisbochs uses MacOSX I imagine the paste works for him. I wonder why it doesn't for you? In any case, insert() is still pretty quick for a couple of sentences of text, so I think using it for 'draft submit' is fine.

**Pull request merged**
